### ISSUE TITLE
Template Import Power Beam AC 7/8

### ISSUE THREAD

**Issue by sayajin101** [tricksol/Zabbix-Templates#1]
Hi There,

If I try import the following templates they all bomb out by the triggers
Template Ubiquiti - Nanostation
Template Ubiquiti - Power Beam AC - 7.0
Template Ubiquiti - Power Beam AC - 8.0
Template Ubiquiti - Rocket AC Lite
Template Ubiquiti - Rocket M

I get the following error
`Incorrect trigger expression. Check expression part starting from " or ({Template Ubiquiti - Power Beam AC - 8.0:ifOutOctets.5.avg(300)} > 75M)".`

If I remove that trigger in question then it has the same issue with the next one.

I am using Zabbix 2.2.13

**Comment by tricksol** [comment]
What version of zabbix are you using? I will check the triggers tonight
by importing them into another zabbix server.
mattOn Wed, 2016-07-06 at 08:36 -0700, Sayajin wrote:

**Comment by tricksol** [comment]
I just imported them into a new zabbix 3.0.3 server with out any
problem. You need to import the airmax templates first if you haven't
already as its a linked template.On Wed, 2016-07-06 at 08:36 -0700, Sayajin wrote:

**Comment by tricksol** [comment]
I need to update the docs, these templates work for 2.4 and on. You can strip out the triggers and import the templates and create your own triggers.

I started on 2.2.6 and then went to 2.4, I must have exported them out of the 2.4 system. Have confirmed that they work on 3.0.3 just now.

**Comment by tytanick** [comment]
Hi guys.
I installed this template, It reads something but yep here is a problem.
It doesnt read constant data but only rare of tries are succesfull.
Anyway my chart has only dots instead of lines becasue it can retrieve too less data.
Any idea what causing it ?
https://tytanick.tinytake.com/sf/MTM4MTkyNl81MDE1NDE4
