### ISSUE TITLE
Shredded data (dots on chart)

### ISSUE THREAD

**Issue by tytanick** [tricksol/Zabbix-Templates#4]
Hi.
I installed this template in zabbix 3.2.
I have problem with it. Using AirOS 8 with Powerbeam.
Its via forwarded on mikrotik snmp port 161.
It reads data but i see it has problem with it becasue only little of retrived data are shown on charts.
Like 1 per 100 request are succesfull.
Thats why i have dots on my charts.
Also snmp ping works ok.
https://tytanick.tinytake.com/sf/MTM4MTkyNl81MDE1NDE4
https://tytanick.tinytake.com/sf/MTM4MTkyOV81MDE1NDMx
https://tytanick.tinytake.com/sf/MTM4MTkzMl81MDE1NDQ0

**Comment by tricksol** [comment]
It's zabbix... turn off the check bulk snmp on the device.

**Comment by tytanick** [comment]
Hehe, i did.
I have unchecked "Use bulk requests" - still nothing :)

**Comment by tytanick** [comment]
I guess this is the problem:
"snmp_parse_oid(): cannot parse OID "UBNT-AirMAX-MIB::ubntWlStatSignal.1"."
But why sometimes it works lol LOL
I downloaded ubiquiti newest MIBs and i wrote them to /usr/share/snmp/..... but still dont know if zabbix is using them. Propably not ?

**Comment by tricksol** [comment]
No it will not you have to tell snmp to use the mib.

**Comment by tricksol** [comment]
This has nothing to do with the template. If the items pull 1 bit of
data the item will say its enable for the host. You might need to check
the "start servers" in the config
